[package]
name = "inox2d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = { version = "0.22.0" }
glutin = { version = "0.30.3", optional = true }
raw-window-handle = "0.5.0"
glutin-winit = { version = "0.2.1", optional = true }
winit = { version = "0.27.5", optional = true }
glow = { version = "0.11.2", optional = true }
image = "0.24.5"
indextree = { version = "4.5.0" }
json = "0.12.4"
nom = "7.1.1"
owo-colors = { version = "3.5.0", optional = true }
thiserror = "1.0.37"
wgpu = { version = "0.14.2", optional = true }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"

[dev-dependencies]
clap = { version = "4.0.26", features = ["derive"] }


[features]
default = ["gl-winit", "wgpu"]
opengl = ["dep:glow"]
gl-winit = ["opengl", "glutin", "glutin-winit", "winit"]
wgpu = ["dep:wgpu"]
owo = ["dep:owo-colors"]

[[example]]
name = "render_inp"
required-features = ["opengl"]
